/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        sazonal: {
          verde: {
            50: '#f0fdf4',
            100: '#dcfce7',
            400: '#4ade80',
            500: '#22c55e',
            600: '#16a34a',
            700: '#15803d',
            dark: '#14532d',
          },
          amarelo: {
            50: '#fefce8',
            100: '#fef9c3',
            400: '#facc15',
            600: '#ca8a04',
            700: '#a16207',
            dark: '#a16207',
          },
          vermelho: {
            50: '#fef2f2',
            100: '#fee2e2',
            400: '#f87171',
            600: '#dc2626',
            700: '#b91c1c',
            dark: '#991b1b',
          },
        },
        'surface-container-highest': '#d4e4fa',
        surface: '#f8f9ff',
        'outline-variant': '#bdcaba',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#002109',
        'inverse-surface': '#233143',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#ffdad6',
        'on-primary-container': '#f7fff2',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#7ffc97',
        'surface-dim': '#ccdbf2',
        background: '#f8f9ff',
        'surface-tint': '#006e2d',
        'on-primary-fixed-variant': '#005320',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#574500',
        secondary: '#735c00',
        'tertiary-fixed-dim': '#ffb4ab',
        'on-primary': '#ffffff',
        'surface-container': '#e5efff',
        'on-surface-variant': '#3e4a3d',
        'on-background': '#0d1c2d',
        'secondary-fixed-dim': '#eec200',
        'on-secondary-fixed': '#231b00',
        'surface-variant': '#d4e4fa',
        'primary-fixed-dim': '#62df7d',
        'surface-container-low': '#eef4ff',
        'on-surface': '#0d1c2d',
        'on-secondary-container': '#6f5900',
        'surface-bright': '#f8f9ff',
        outline: '#6e7b6c',
        'primary-container': '#00873a',
        tertiary: '#bb0112',
        'inverse-primary': '#62df7d',
        'inverse-on-surface': '#e9f1ff',
        'tertiary-container': '#e02928',
        'on-error': '#ffffff',
        'secondary-fixed': '#ffe083',
        'on-tertiary-container': '#fffbff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#410002',
        'surface-container-high': '#dbe9ff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#93000b',
        'secondary-container': '#fed01b',
        primary: '#006b2c',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        sm: '8px',
        xs: '4px',
        xl: '32px',
        lg: '24px',
        'margin-mobile': '20px',
        md: '16px',
        unit: '4px',
        gutter: '16px',
      },
      fontFamily: {
        'body-md': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
      },
      boxShadow: {
        'clay-dark':
          'inset -6px -6px 12px rgba(255, 255, 255, 0.4), inset 6px 6px 12px rgba(0, 0, 0, 0.1), 4px 4px 10px rgba(0, 0, 0, 0.05)',
        'clay-green':
          'inset -6px -6px 12px rgba(255, 255, 255, 0.3), inset 6px 6px 12px rgba(0, 107, 44, 0.2), 4px 4px 10px rgba(0, 107, 44, 0.15)',
        'clay-pressed':
          'inset 6px 6px 12px rgba(0, 0, 0, 0.1), inset -6px -6px 12px rgba(255, 255, 255, 0.4)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
