-- ============================================================================
-- MIGRATION 82 — Refinamento Estatístico, Normalização de Grandezas e
--                Data Healing (Semáforo Sensível por Coeficiente de Variação)
-- ============================================================================
-- Contexto: a fact é poluída por preços de grandezas diferentes (PITAYA que
-- varia de R$ 0,01 a R$ 108 dependendo da unidade da coleta — caixa, kg,
-- unidade). O semáforo clássico ±desvio vira VERMELHO/VERDE espúrio.
--
-- Decisão (definitiva):
--   1) GRANULARIDADE NA FACT: staging.fact_precos_mensais passa a carregar
--      unidade_canonica + fator_kg + fluxo_unidade; o UNIQUE vira
--      (id_produto, id_localidade, ano, mes, COALESCE(unidade_canonica,'kg')).
--   2) SAZONALIDADE ESCOLHE KG: mart.sazonalidade_produto mantém o UNIQUE
--      atual (1 linha/mês) e a SP escolhe a linha por DISTINCT ON com
--      prioridade kg > fator_kg conhecido > genérico.
--   3) Semáforo passa a usar a BANDA PROPORCIONAL ao coeficiente de variação
--      (CV) da série de 24 meses, com piso de faixa por magnitude de preço.
--
-- Fases:
--   Fase 1 (pipeline/etl_conab_diario.py) — transform per-unidade (feita).
--   Fase 2 — DDL: mart.dim_unidade_medida + seeds + ALTER fact + normalizador SQL.
--   Fase 3 — Motor matemático CV: estatisticas_volatilidade_24m_cv() +
--            calcular_semaforo_preco_sensivel() (+ retrocompat 3-arg).
--   Fase 4 — Backfill da unidade na fact (ANTES da mudança de UNIQUE).
--   Fase 5 — Procedure central sp_calcular_sazonalidade (kg-first + CV).
--   Fase 6 — Validation Gate: ops.simulacao_semaforo_v82.
--   Rollback — instruções comentadas no fim.
--
-- Execução: 1x, na ordem do arquivo (idempotente). NÃO sobrescreve
-- unidade_canonica já preenchida na fact.

-- ============================================================================
-- FASE 2 — DDL, dimensão de unidades e normalizador SQL
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS mart;
CREATE SCHEMA IF NOT EXISTS staging;

-- ---------------------------------------------------------------------------
-- 2.1 — mart.dim_unidade_medida (dimensão canônica de unidades)
-- ---------------------------------------------------------------------------
-- unidade_canonica: nome canônico da unidade (ex.: kg, cx20, saco50,
-- caixa_generica, und, dz). fator_kg: conversão para quilograma
-- (NULL = não conversível com segurança → eh_confiavel = false).
-- sinonimos: variações observadas nas coletas (lowercase).

CREATE TABLE IF NOT EXISTS mart.dim_unidade_medida (
    id_unidade       SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_canonica TEXT NOT NULL,
    sinonimos        TEXT[] NOT NULL DEFAULT '{}',
    fator_kg         NUMERIC(12,6),
    eh_confiavel     BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_dim_unidade_medida UNIQUE (unidade_canonica)
);

COMMENT ON TABLE mart.dim_unidade_medida IS
    'Dimensão canônica de unidades de medida e fatores de conversão para kg. '
    'Alimentada pela Migration 82 (seeds) e pelo ETL diário (normalizar_unidade_sig).';

COMMENT ON COLUMN mart.dim_unidade_medida.eh_confiavel IS
    'false quando a unidade não tem fator_kg confiável (caixa/saco genéricos, '
    'unidade, dúzia) — séries com mistura dessas grandezas contaminam o CV.';

-- Seeds (idempotentes — 2ª execução vira no-op com DO UPDATE)
INSERT INTO mart.dim_unidade_medida (unidade_canonica, sinonimos, fator_kg, eh_confiavel)
VALUES
    ('kg',             ARRAY['kg','kilo','quilograma','quilo'],                1.0,       TRUE),
    ('g',              ARRAY['g','grama','gramas'],                            0.001,     TRUE),
    ('ton',            ARRAY['ton','tonelada','toneladas','t'],                1000.0,    TRUE),
    ('arroba',         ARRAY['@','arroba','arrobas'],                          15.0,      TRUE),
    ('cx20',           ARRAY['cx 20kg','cx20kg','caixa 20kg','cx 20'],         20.0,      TRUE),
    ('cx22',           ARRAY['cx 22kg','cx22kg','caixa 22kg','cx 22'],         22.0,      TRUE),
    ('cx25',           ARRAY['cx 25kg','cx25kg','caixa 25kg','cx 25'],         25.0,      TRUE),
    ('cx30',           ARRAY['cx 30kg','cx30kg','caixa 30kg','cx 30'],         30.0,      TRUE),
    ('caixa_generica', ARRAY['cx','caixa','cxa','cx15','cx 15'],               NULL,      FALSE),
    ('saco50',         ARRAY['saco 50kg','saco50kg','sacaria 50kg','saco 50'], 50.0,      TRUE),
    ('saco25',         ARRAY['saco 25kg','saco25kg','sacaria 25kg','saco 25'], 25.0,      TRUE),
    ('saco_generico',  ARRAY['saco','sacaria','sc','saco 30','saco30'],        NULL,      FALSE),
    ('und',            ARRAY['un','und','unidade','unid','pc','pto','maço','maco'], NULL, FALSE),
    ('dz',             ARRAY['dz','duzia','dúzia'],                            NULL,      FALSE)
ON CONFLICT (unidade_canonica) DO UPDATE SET
    sinonimos    = EXCLUDED.sinonimos,
    fator_kg     = EXCLUDED.fator_kg,
    eh_confiavel = EXCLUDED.eh_confiavel;

-- ---------------------------------------------------------------------------
-- 2.2 — ALTER staging.fact_precos_mensais (colunas de unidade)
-- ---------------------------------------------------------------------------

ALTER TABLE staging.fact_precos_mensais
    ADD COLUMN IF NOT EXISTS unidade_canonica TEXT,
    ADD COLUMN IF NOT EXISTS fator_kg         NUMERIC(12,6),
    ADD COLUMN IF NOT EXISTS fluxo_unidade    TEXT;

COMMENT ON COLUMN staging.fact_precos_mensais.unidade_canonica IS
    'Unidade canônica do preço da linha (kg, cx20, saco50, und, dz, ...). '
    'NULL = ainda não classificado (backfill da Migration 82 preenche).';
COMMENT ON COLUMN staging.fact_precos_mensais.fator_kg IS
    'Fator de conversão do preço_medio para R$/kg. NULL = unidade não '
    'conversível com segurança.';
COMMENT ON COLUMN staging.fact_precos_mensais.fluxo_unidade IS
    'Origem da classificação da unidade: etl (normalizador diário) ou '
    'inferido_backfill (heuristicas da Migration 82).';

-- ---------------------------------------------------------------------------
-- 2.3 — staging.normalizar_unidade_sql(p_unidade) — espelho SQL do Python
-- ---------------------------------------------------------------------------
-- Espelho da função Python normalizar_unidade_sig() do ETL diário:
--  1. match direto por sinonimo/canonico na dim (normaliza espelhos)
--  2. regex "N kg" → kg com fator N
--  3. fallback: unidade crua lowercase, fator NULL, nao confiavel.

CREATE OR REPLACE FUNCTION staging.normalizar_unidade_sql(p_unidade TEXT)
RETURNS TABLE (unidade_canonica TEXT, fator_kg NUMERIC, eh_confiavel BOOLEAN)
LANGUAGE sql
STABLE
AS $$
    WITH sig AS (
        SELECT LOWER(BTRIM(COALESCE(p_unidade, ''))) AS s
    ),
    direto AS (
        SELECT um.unidade_canonica, um.fator_kg, um.eh_confiavel
        FROM mart.dim_unidade_medida um, sig
        WHERE sig.s = um.unidade_canonica
           OR sig.s = ANY(um.sinonimos)
        LIMIT 1
    ),
    regex_kg AS (
        SELECT 'kg'::TEXT AS unidade_canonica,
               (REGEXP_MATCH(sig.s, '^(\d+)\s*kg\b'))[1]::NUMERIC AS fator_kg,
               TRUE AS eh_confiavel
        FROM sig
        WHERE sig.s ~ '^(\d+)\s*kg\b'
    )
    SELECT
        COALESCE(d.unidade_canonica, r.unidade_canonica, s.s) AS unidade_canonica,
        COALESCE(d.fator_kg, r.fator_kg)                       AS fator_kg,
        COALESCE(d.eh_confiavel, r.eh_confiavel, FALSE)        AS eh_confiavel
    FROM sig s
    LEFT JOIN direto d ON TRUE
    LEFT JOIN regex_kg r ON TRUE;
$$;

COMMENT ON FUNCTION staging.normalizar_unidade_sql(TEXT) IS
    'Espelho SQL do normalizador Python do ETL diário CONAB. Prioridade: '
    '(1) match direto na dim_unidade_medida por sinonimo/canonico; '
    '(2) regex "^N kg" → kg com fator N; (3) fallback: unidade crua '
    'lowercase com fator NULL. Uso: SELECT * FROM staging.normalizar_unidade_sql(''cx 20kg'');';

GRANT EXECUTE ON FUNCTION staging.normalizar_unidade_sql(TEXT) TO role_etl_writer;
GRANT SELECT ON mart.dim_unidade_medida TO role_api_reader, role_etl_writer;

-- ============================================================================
-- FASE 3 — Motor matemático: estatísticas com CV e semáforo sensível
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 3.1 — staging.estatisticas_volatilidade_24m_cv()
-- ---------------------------------------------------------------------------
-- Evolução de estatisticas_volatilidade_24m() (migrations 65/68):
--  * mesma janela (24m reais), mesmo piso de sanidade (preco >= 0.50),
--    mesmo IQR de Tukey + guard robusto (preco >= 0.25 * mediana) — todos os
--    cálculos sobre preco_por_kg.
--  * NOVO: normaliza a série para preco_por_kg ANTES das estatísticas usando
--    mart.fator_kg_produto_uf (fator por produto+UF) — abordagem C da
--    Migration 53 (preco_medio / fator_kg). Sem fator conhecido, usa o
--    preco cru (mistura de grandezas permanece → contam_unidade = true).
--  * NOVO: cv_serie = desvio_padrao_historico / media_historica e
--    contam_unidade = cv_serie > 0.40 (sinal de série com grandezas mistas).

CREATE OR REPLACE FUNCTION staging.estatisticas_volatilidade_24m_cv()
RETURNS TABLE (
    id_produto              INTEGER,
    id_localidade           INTEGER,
    media_historica         NUMERIC(14,4),
    desvio_padrao_historico NUMERIC(14,4),
    n_meses                 INTEGER,
    cv_serie                NUMERIC(14,4),
    contam_unidade          BOOLEAN,
    desvio_efetivo          NUMERIC(14,4)
)
LANGUAGE sql
STABLE
AS $$
    WITH max_data AS (
        SELECT MAX(ano * 12 + mes) AS max_periodo
        FROM staging.fact_precos_mensais
    ),
    -- Janela bruta: últimos 24 meses reais, piso absoluto de sanidade.
    -- preco_por_kg: normaliza grandezas quando existe fator empírico
    -- (fator_kg_produto_uf) — sem fator, mantém o preco cru (CV alto).
    janela AS (
        SELECT
            f.id_produto,
            f.id_localidade,
            COALESCE(
                f.preco_medio / NULLIF(fk.fator_kg, 0),
                f.preco_medio
            ) AS preco_por_kg
        FROM staging.fact_precos_mensais f
        JOIN staging.dim_localidade l ON l.id_localidade = f.id_localidade
        LEFT JOIN mart.fator_kg_produto_uf fk
            ON fk.id_produto = f.id_produto
           AND fk.uf         = l.uf
        CROSS JOIN max_data m
        WHERE f.ano * 12 + f.mes > m.max_periodo - 24
          AND f.preco_medio >= 0.50
    ),
    quartis AS (
        SELECT
            j.id_produto,
            j.id_localidade,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY j.preco_por_kg) AS q1,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY j.preco_por_kg) AS q3,
            PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY j.preco_por_kg) AS mediana
        FROM janela j
        GROUP BY j.id_produto, j.id_localidade
    ),
    janela_limpa AS (
        SELECT
            j.id_produto,
            j.id_localidade,
            j.preco_por_kg
        FROM janela j
        JOIN quartis q
            ON q.id_produto = j.id_produto
           AND q.id_localidade = j.id_localidade
        WHERE q.q1 IS NOT NULL AND q.q3 IS NOT NULL
          AND j.preco_por_kg BETWEEN (q.q1 - 1.5 * (q.q3 - q.q1))
                                 AND (q.q3 + 1.5 * (q.q3 - q.q1))
          AND (q.mediana IS NULL OR j.preco_por_kg >= 0.25 * q.mediana)
    )
    SELECT
        j.id_produto,
        j.id_localidade,
        AVG(j.preco_por_kg)::NUMERIC(14,4)            AS media_historica,
        STDDEV(j.preco_por_kg)::NUMERIC(14,4)         AS desvio_padrao_historico,
        COUNT(*)::INTEGER                             AS n_meses,
        CASE
            WHEN AVG(j.preco_por_kg) IS NULL OR AVG(j.preco_por_kg) = 0 THEN NULL
            ELSE (STDDEV(j.preco_por_kg) / AVG(j.preco_por_kg))::NUMERIC(14,4)
        END                                           AS cv_serie,
        CASE
            WHEN AVG(j.preco_por_kg) IS NULL OR AVG(j.preco_por_kg) = 0 THEN NULL
            ELSE (STDDEV(j.preco_por_kg) / AVG(j.preco_por_kg)) > 0.40
        END                                           AS contam_unidade,
        CASE
            WHEN AVG(j.preco_por_kg) IS NULL OR AVG(j.preco_por_kg) = 0 THEN NULL
            WHEN STDDEV(j.preco_por_kg) IS NULL
              OR STDDEV(j.preco_por_kg) = 0
              OR (STDDEV(j.preco_por_kg) / AVG(j.preco_por_kg)) < 0.10
                THEN ROUND(0.10 * AVG(j.preco_por_kg), 4)   -- piso CV mínimo 10%
            ELSE STDDEV(j.preco_por_kg)
        END::NUMERIC(14,4)                            AS desvio_efetivo
    FROM janela_limpa j
    GROUP BY j.id_produto, j.id_localidade;
$$;

COMMENT ON FUNCTION staging.estatisticas_volatilidade_24m_cv() IS
    'Estatísticas de volatilidade por (produto, localidade) sobre os últimos '
    '24 meses reais, calculadas sobre preco_por_kg (normalização via '
    'mart.fator_kg_produto_uf — abordagem C da Migration 53). Mesma janela, '
    'piso >= 0.50, IQR de Tukey e guard robusto 0.25*mediana da migration 68. '
    'NOVO: cv_serie = desvio/media e contam_unidade = cv > 0.40 (grandezas '
    'mistas na série). Uso: SELECT * FROM staging.estatisticas_volatilidade_24m_cv();';

GRANT EXECUTE ON FUNCTION staging.estatisticas_volatilidade_24m_cv()
    TO role_etl_writer;

-- ---------------------------------------------------------------------------
-- 3.2 — staging.calcular_semaforo_preco_sensivel(...)
-- ---------------------------------------------------------------------------
-- Semáforo por BANDA PROPORCIONAL ao CV (coeficiente de variação da série):
--   banda = referência * (1 ± cv_efetivo)
-- onde cv_efetivo = GREATEST(COALESCE(cv_serie, 0), piso_da_faixa) e o piso
-- da faixa depende da magnitude do preço de referência:
--   ref <= 5.00         → piso 0.02 (±2%)
--   ref > 5.00 e <=20   → piso 0.05 (±5%)
--   ref > 20.00         → piso 0.08 (±8%)
-- Regras:
--   * qualquer argumento NULL ou <= 0 → NULL (chamador aplica fallback, AMARELO)
--   * cv_efetivo > 0.40 → AMARELO defensivo (série com grandezas mistas:
--     semáforo nunca vibra VERDE/VERMELHO sobre estatística não confiável)
--   * preco < ref*(1-cv_efetivo) → VERDE
--   * preco > ref*(1+cv_efetivo) → VERMELHO
--   * senão → AMARELO
-- p_fator_kg (DEFAULT 1): aplicado sobre preco e referência ANTES da banda,
-- permitindo comparar grandezas diferentes (ex.: preço de caixa vs. ref kg).

CREATE OR REPLACE FUNCTION staging.calcular_semaforo_preco_sensivel(
    p_preco_exibido    NUMERIC,
    p_preco_referencia NUMERIC,
    p_cv_serie         NUMERIC,
    p_fator_kg         NUMERIC DEFAULT 1
)
RETURNS TEXT
LANGUAGE sql
STABLE
AS $$
    WITH cv AS (
        SELECT GREATEST(
            COALESCE(p_cv_serie, 0),
            CASE
                WHEN p_preco_referencia IS NULL OR p_preco_referencia <= 0 THEN 0
                WHEN p_preco_referencia <= 5.00 THEN 0.02
                WHEN p_preco_referencia <= 20.00 THEN 0.05
                ELSE 0.08
            END
        ) AS cv_efetivo
    )
    SELECT CASE
        WHEN p_preco_exibido IS NULL OR p_preco_exibido <= 0 THEN NULL
        WHEN p_preco_referencia IS NULL OR p_preco_referencia <= 0 THEN NULL
        WHEN p_fator_kg IS NULL OR p_fator_kg <= 0 THEN NULL
        WHEN cv.cv_efetivo > 0.40 THEN 'AMARELO'
        WHEN (p_preco_exibido / p_fator_kg)
             < ((p_preco_referencia / p_fator_kg) * (1 - cv.cv_efetivo)) THEN 'VERDE'
        WHEN (p_preco_exibido / p_fator_kg)
             > ((p_preco_referencia / p_fator_kg) * (1 + cv.cv_efetivo)) THEN 'VERMELHO'
        ELSE 'AMARELO'
    END
    FROM cv;
$$;

COMMENT ON FUNCTION staging.calcular_semaforo_preco_sensivel(NUMERIC, NUMERIC, NUMERIC, NUMERIC) IS
    'Semáforo sensível por coeficiente de variação (Migration 82). Banda '
    'proporcional: ref * (1 ± cv_efetivo), com cv_efetivo = GREATEST(cv_serie, '
    'piso_da_faixa) e piso por magnitude (<=5 → 0.02; <=20 → 0.05; >20 → 0.08). '
    'cv_efetivo > 0.40 → AMARELO defensivo (grandezas mistas). p_fator_kg '
    'normaliza preço e referência para comparar grandezas diferentes. '
    'Retorna NULL se qualquer argumento for NULL ou <= 0.';

GRANT EXECUTE ON FUNCTION staging.calcular_semaforo_preco_sensivel(NUMERIC, NUMERIC, NUMERIC, NUMERIC)
    TO role_etl_writer;

-- ---------------------------------------------------------------------------
-- 3.3 — RETROCOMPAT: staging.calcular_semaforo_preco(NUMERIC, NUMERIC, NUMERIC)
-- ---------------------------------------------------------------------------
-- Mantém a assinatura de 3 argumentos (usada por views/SP legadas): deriva o
-- cv a partir do desvio (cv = desvio / referencia, NULL-safe) e delega para a
-- versão sensível. Comportamento equivalente à antiga banda absoluta ±desvio
-- quando o desvio é confiável; ganha os pisos de faixa quando o desvio é baixo.

CREATE OR REPLACE FUNCTION staging.calcular_semaforo_preco(
    p_preco_exibido    NUMERIC,
    p_preco_referencia NUMERIC,
    p_desvio_padrao    NUMERIC
)
RETURNS TEXT
LANGUAGE sql
STABLE
AS $$
    SELECT staging.calcular_semaforo_preco_sensivel(
        p_preco_exibido,
        p_preco_referencia,
        CASE
            WHEN p_preco_referencia IS NULL OR p_preco_referencia = 0 THEN NULL
            WHEN p_desvio_padrao IS NULL THEN NULL
            ELSE p_desvio_padrao / p_preco_referencia
        END,
        1
    );
$$;

COMMENT ON FUNCTION staging.calcular_semaforo_preco(NUMERIC, NUMERIC, NUMERIC) IS
    'RETROCOMPAT da Migration 82: deriva o CV (desvio/referencia, NULL-safe) '
    'e delega para staging.calcular_semaforo_preco_sensivel(). Mantém a '
    'assinatura de 3 argumentos para chamadores legados.';

GRANT EXECUTE ON FUNCTION staging.calcular_semaforo_preco(NUMERIC, NUMERIC, NUMERIC)
    TO role_etl_writer;

-- ============================================================================
-- FASE 4 — Backfill de unidade na fact + mudança do UNIQUE
-- ============================================================================
-- Regra (por (id_produto, uf), mediana em R$/kg de referência):
--   preco_medio >  10 * mediana  → 'cx' (caixa; fator_kg empírico quando
--                                     existir em fator_kg_produto_uf)
--   preco_medio <   0.50         → 'un' (unidade; sem fator confiável)
--   senão                        → 'kg' (fator 1)
-- Fluxo: 'inferido_backfill'. NUNCA sobrescreve unidade_canonica preenchida.

DO $$
DECLARE
    v_total     BIGINT;
    v_kg        BIGINT;
    v_cx        BIGINT;
    v_un        BIGINT;
    v_inicio    TIMESTAMPTZ := clock_timestamp();
    v_fim       TIMESTAMPTZ;
BEGIN
    RAISE NOTICE '[migration_82] Iniciando backfill de unidade na fact...';

    WITH mediana_per_kg AS (
        SELECT
            f.id_produto,
            l.uf,
            COALESCE(
                fk.mediana_preco_medio,
                PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY f.preco_medio)
            ) AS mediana
        FROM staging.fact_precos_mensais f
        JOIN staging.dim_localidade l ON l.id_localidade = f.id_localidade
        LEFT JOIN mart.fator_kg_produto_uf fk
            ON fk.id_produto = f.id_produto
           AND fk.uf         = l.uf
        GROUP BY f.id_produto, l.uf, fk.mediana_preco_medio
    ),
    classificada AS (
        SELECT
            f.id_fato,
            f.id_produto,
            l.uf,
            CASE
                WHEN mp.mediana IS NOT NULL AND f.preco_medio > 10 * mp.mediana THEN 'cx'
                WHEN f.preco_medio < 0.50 THEN 'un'
                ELSE 'kg'
            END AS unidade_canonica,
            CASE
                WHEN mp.mediana IS NOT NULL AND f.preco_medio > 10 * mp.mediana
                    THEN fk2.fator_kg
                WHEN f.preco_medio < 0.50 THEN NULL
                ELSE 1
            END AS fator_kg,
            'inferido_backfill' AS fluxo_unidade
        FROM staging.fact_precos_mensais f
        JOIN staging.dim_localidade l ON l.id_localidade = f.id_localidade
        LEFT JOIN mediana_per_kg mp
            ON mp.id_produto = f.id_produto AND mp.uf = l.uf
        LEFT JOIN mart.fator_kg_produto_uf fk2
            ON fk2.id_produto = f.id_produto AND fk2.uf = l.uf
        WHERE f.unidade_canonica IS NULL
          AND f.preco_medio IS NOT NULL
    )
    UPDATE staging.fact_precos_mensais f
    SET unidade_canonica = c.unidade_canonica,
        fator_kg         = c.fator_kg,
        fluxo_unidade    = c.fluxo_unidade
    FROM classificada c
    WHERE f.id_fato = c.id_fato;

    GET DIAGNOSTICS v_total = ROW_COUNT;

    SELECT COUNT(*) INTO v_kg FROM staging.fact_precos_mensais
        WHERE unidade_canonica = 'kg' AND fluxo_unidade = 'inferido_backfill';
    SELECT COUNT(*) INTO v_cx FROM staging.fact_precos_mensais
        WHERE unidade_canonica = 'cx' AND fluxo_unidade = 'inferido_backfill';
    SELECT COUNT(*) INTO v_un FROM staging.fact_precos_mensais
        WHERE unidade_canonica = 'un' AND fluxo_unidade = 'inferido_backfill';

    v_fim := clock_timestamp();
    RAISE NOTICE '[migration_82] Backfill: % linhas em %s seg | kg=%, cx=%, un=%',
        v_total, ROUND(EXTRACT(EPOCH FROM v_fim - v_inicio)::NUMERIC, 2),
        v_kg, v_cx, v_un;
    RAISE NOTICE '[migration_82] Linhas com unidade_canonica NULL (órfãs): %',
        (SELECT COUNT(*) FROM staging.fact_precos_mensais WHERE unidade_canonica IS NULL);
END $$;

-- ---------------------------------------------------------------------------
-- Mudança do UNIQUE (DEPOIS do backfill)
-- ---------------------------------------------------------------------------
-- Remove a constraint antiga de 4 colunas e cria UNIQUE INDEX com a
-- expressão COALESCE(unidade_canonica, 'kg'). IMPORTANTE: PostgreSQL não
-- aceita expressão em UNIQUE CONSTRAINT (só índices). Todo writer que use
-- ON CONFLICT (id_produto, id_localidade, ano, mes) precisa migrar para a
-- forma de expressão (ver Riscos no contrato).

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_fact_precos_mensais'
          AND connamespace = 'staging'::regnamespace
    ) THEN
        ALTER TABLE staging.fact_precos_mensais
            DROP CONSTRAINT uq_fact_precos_mensais;
        RAISE NOTICE '[migration_82] Constraint uq_fact_precos_mensais removida.';
    END IF;
END $$;

DROP INDEX IF EXISTS uq_fact_precos_mensais_unidade;
CREATE UNIQUE INDEX uq_fact_precos_mensais_unidade
    ON staging.fact_precos_mensais
       (id_produto, id_localidade, ano, mes, COALESCE(unidade_canonica, 'kg'));

COMMENT ON INDEX staging.uq_fact_precos_mensais_unidade IS
    'Migration 82: UNIQUE com unidade (COALESCE(unidade_canonica,''kg'')) — '
    'permite 1 linha/mês por unidade. Writers com ON CONFLICT devem usar '
    'ON CONFLICT (id_produto, id_localidade, ano, mes, (COALESCE(unidade_canonica, ''kg''))).';

-- ============================================================================
-- FASE 5 — Procedure central sp_calcular_sazonalidade (kg-first + CV)
-- ============================================================================

ALTER TABLE mart.sazonalidade_produto
    ADD COLUMN IF NOT EXISTS cv_serie       NUMERIC(14,4),
    ADD COLUMN IF NOT EXISTS contam_unidade BOOLEAN;

COMMENT ON COLUMN mart.sazonalidade_produto.cv_serie IS
    'Coeficiente de variação da série de 24 meses (Migration 82). NULL quando '
    'a série não tem estatística.';
COMMENT ON COLUMN mart.sazonalidade_produto.contam_unidade IS
    'true quando cv_serie > 0.40 (série com grandezas mistas) — status_cor '
    'vira AMARELO defensivo e metadado_transparencia ganha aviso.';

-- ---------------------------------------------------------------------------
-- Reescrita da SP: escolhe a linha kg-first ANTES da média móvel e usa o
-- semáforo sensível por CV.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE staging.sp_calcular_sazonalidade(IN p_ano_alvo smallint DEFAULT NULL::smallint, IN p_mes_alvo smallint DEFAULT NULL::smallint)
 LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_ano    SMALLINT;
    v_mes    SMALLINT;
    v_inicio TIMESTAMPTZ;
    v_fim    TIMESTAMPTZ;
    v_total  INTEGER;
BEGIN
    v_inicio := clock_timestamp();

    IF p_ano_alvo IS NULL OR p_mes_alvo IS NULL THEN
        SELECT MAX(ano), MAX(mes) INTO v_ano, v_mes
        FROM staging.fact_precos_mensais;
    ELSE
        v_ano := p_ano_alvo;
        v_mes := p_mes_alvo;
    END IF;

    RAISE NOTICE '[sp_calcular_sazonalidade] Alvo: %-% (regra CV v82)', v_ano, v_mes;

    INSERT INTO mart.sazonalidade_produto (
        id_produto, id_localidade, ano, mes,
        preco_medio, media_movel_12m, indice_sazonalidade,
        status_cor, fonte, calculado_em,
        preco_atual, preco_referencia,
        desvio_padrao_historico, limite_superior, limite_inferior,
        preco_mes_anterior, variacao_mom_pct,
        data_referencia_atual,
        cv_serie, contam_unidade, metadado_transparencia
    )
    WITH fact_kg AS (
        -- Escolhe UMA linha por (produto, localidade, ano, mes) com prioridade
        -- kg > fator_kg conhecido > genérico. A média móvel e o índice
        -- sazonal são calculados sobre a série JÁ escolhida.
        SELECT DISTINCT ON (f.id_produto, f.id_localidade, f.ano, f.mes)
            f.id_produto,
            f.id_localidade,
            f.ano,
            f.mes,
            f.preco_medio,
            f.unidade_canonica,
            f.fator_kg
        FROM staging.fact_precos_mensais f
        WHERE (f.ano < v_ano OR (f.ano = v_ano AND f.mes <= v_mes))
          AND f.preco_medio IS NOT NULL
        ORDER BY
            f.id_produto,
            f.id_localidade,
            f.ano,
            f.mes,
            CASE
                WHEN f.unidade_canonica = 'kg' THEN 0
                WHEN f.fator_kg IS NOT NULL THEN 1
                ELSE 2
            END,
            f.unidade_canonica
    ),
    precos_12m AS (
        SELECT
            f.id_produto,
            f.id_localidade,
            f.ano,
            f.mes,
            f.preco_medio,
            AVG(f.preco_medio) OVER (
                PARTITION BY f.id_produto, f.id_localidade
                ORDER BY f.ano, f.mes
                ROWS BETWEEN 11 PRECEDING AND CURRENT ROW
            ) AS media_movel_12m,
            COUNT(*) OVER (
                PARTITION BY f.id_produto, f.id_localidade
                ORDER BY f.ano, f.mes
                ROWS BETWEEN 11 PRECEDING AND CURRENT ROW
            ) AS meses_no_window,
            LAG(f.preco_medio) OVER (
                PARTITION BY f.id_produto, f.id_localidade
                ORDER BY f.ano, f.mes
            ) AS preco_mes_anterior
        FROM fact_kg f
    ),
    volatilidade AS MATERIALIZED (
        SELECT * FROM staging.estatisticas_volatilidade_24m_cv()
    )
    SELECT
        p.id_produto,
        p.id_localidade,
        p.ano,
        p.mes,
        p.preco_medio,
        p.media_movel_12m,
        CASE
            WHEN p.media_movel_12m IS NOT NULL AND p.media_movel_12m > 0
            THEN ROUND(p.preco_medio / p.media_movel_12m, 4)
            ELSE NULL
        END AS indice_sazonalidade,
        CASE
            WHEN p.meses_no_window < 6 THEN 'AMARELO'
            WHEN v.contam_unidade THEN 'AMARELO'
            WHEN v.desvio_efetivo IS NULL THEN 'AMARELO'
            ELSE COALESCE(
                staging.calcular_semaforo_preco_sensivel(
                    p.preco_medio, p.media_movel_12m, v.cv_serie, 1
                ),
                'AMARELO'
            )
        END AS status_cor,
        'municipio' AS fonte,
        NOW() AS calculado_em,
        p.preco_medio AS preco_atual,
        p.preco_medio AS preco_referencia,
        v.desvio_efetivo AS desvio_padrao_historico,
        p.media_movel_12m + v.desvio_efetivo AS limite_superior,
        p.media_movel_12m - v.desvio_efetivo AS limite_inferior,
        p.preco_mes_anterior,
        CASE
            WHEN p.preco_mes_anterior IS NULL OR p.preco_mes_anterior <= 0
                 OR p.preco_medio IS NULL OR p.preco_medio <= 0
            THEN NULL
            ELSE ROUND(((p.preco_medio / p.preco_mes_anterior) - 1) * 100, 4)
        END AS variacao_mom_pct,
        p.ano::TEXT || '-' || LPAD(p.mes::TEXT, 2, '0') AS data_referencia_atual,
        v.cv_serie,
        v.contam_unidade,
        CASE
            WHEN v.contam_unidade THEN
                jsonb_build_object(
                    'regra', 'cv_sensivel_v82',
                    'contam_unidade', v.contam_unidade,
                    'aviso', 'serie temporal com mistura de grandezas -> baixa confiabilidade estatistica'
                )
            ELSE NULL
        END AS metadado_transparencia
    FROM precos_12m p
    LEFT JOIN LATERAL (
        SELECT st.cv_serie, st.contam_unidade, st.desvio_efetivo
        FROM volatilidade st
        WHERE st.id_produto = p.id_produto
          AND st.id_localidade = p.id_localidade
    ) v ON TRUE
    WHERE p.ano = v_ano AND p.mes = v_mes
    ON CONFLICT (id_produto, id_localidade, ano, mes)
    DO UPDATE SET
        preco_medio         = EXCLUDED.preco_medio,
        media_movel_12m     = EXCLUDED.media_movel_12m,
        indice_sazonalidade = EXCLUDED.indice_sazonalidade,
        status_cor          = EXCLUDED.status_cor,
        fonte               = EXCLUDED.fonte,
        calculado_em        = NOW(),
        preco_atual         = EXCLUDED.preco_atual,
        preco_referencia    = EXCLUDED.preco_referencia,
        desvio_padrao_historico = EXCLUDED.desvio_padrao_historico,
        limite_superior     = EXCLUDED.limite_superior,
        limite_inferior     = EXCLUDED.limite_inferior,
        preco_mes_anterior  = EXCLUDED.preco_mes_anterior,
        variacao_mom_pct    = EXCLUDED.variacao_mom_pct,
        data_referencia_atual = EXCLUDED.data_referencia_atual,
        cv_serie            = EXCLUDED.cv_serie,
        contam_unidade      = EXCLUDED.contam_unidade,
        metadado_transparencia = CASE
            WHEN EXCLUDED.contam_unidade THEN EXCLUDED.metadado_transparencia
            ELSE mart.sazonalidade_produto.metadado_transparencia
        END;

    GET DIAGNOSTICS v_total = ROW_COUNT;
    v_fim := clock_timestamp();

    RAISE NOTICE '[sp_calcular_sazonalidade] Concluído: % linhas em % seg',
        v_total, ROUND(EXTRACT(EPOCH FROM v_fim - v_inicio)::NUMERIC, 2);
END;
$procedure$;

-- ============================================================================
-- FASE 6 — Validation Gate: ops.simulacao_semaforo_v82
-- ============================================================================
-- View de auditoria: compara o status_cor ATUAL (regra antiga) com o
-- status_cor que a regra sensível por CV produziria, expõe cv_real,
-- contam_unidade, unidade_inferida e metadado_transparencia. Prioriza
-- maiores |preco_atual - preco_referencia| e produtos PITAYA/BATATA/ALFACE.
-- LIMIT 1000 — as linhas mais críticas.

CREATE OR REPLACE VIEW ops.simulacao_semaforo_v82 AS
WITH volatilidade AS MATERIALIZED (
    SELECT * FROM staging.estatisticas_volatilidade_24m_cv()
),
unidade_fact AS (
    SELECT DISTINCT ON (f.id_produto, f.id_localidade, f.ano, f.mes)
        f.id_produto,
        f.id_localidade,
        f.ano,
        f.mes,
        f.unidade_canonica,
        f.fator_kg
    FROM staging.fact_precos_mensais f
    ORDER BY
        f.id_produto,
        f.id_localidade,
        f.ano,
        f.mes,
        CASE
            WHEN f.unidade_canonica = 'kg' THEN 0
            WHEN f.fator_kg IS NOT NULL THEN 1
            ELSE 2
        END,
        f.unidade_canonica
)
SELECT
    s.id_produto,
    s.id_localidade,
    s.ano,
    s.mes,
    s.status_cor                                                                 AS status_cor_antigo,
    CASE
        WHEN v.contam_unidade THEN 'AMARELO'
        WHEN v.desvio_efetivo IS NULL THEN 'AMARELO'
        ELSE COALESCE(
            staging.calcular_semaforo_preco_sensivel(
                s.preco_medio, s.media_movel_12m, v.cv_serie, 1
            ),
            'AMARELO'
        )
    END                                                                          AS status_cor_novo,
    v.cv_serie                                                                   AS cv_real,
    v.contam_unidade,
    uf.unidade_canonica                                                          AS unidade_inferida,
    uf.fator_kg,
    s.metadado_transparencia,
    ABS(s.preco_medio - COALESCE(s.media_movel_12m, s.preco_medio))              AS distancia_referencia,
    (UPPER(dp.nome_produto) LIKE '%PITAYA%'
        OR UPPER(dp.nome_produto) LIKE '%BATATA%'
        OR UPPER(dp.nome_produto) LIKE '%ALFACE%')                              AS prioridade_alvo,
    s.status_cor IS DISTINCT FROM
        (CASE
            WHEN v.contam_unidade THEN 'AMARELO'
            WHEN v.desvio_efetivo IS NULL THEN 'AMARELO'
            ELSE COALESCE(
                staging.calcular_semaforo_preco_sensivel(
                    s.preco_medio, s.media_movel_12m, v.cv_serie, 1
                ),
                'AMARELO'
            )
        END)                                                                    AS mudou_status
FROM mart.sazonalidade_produto s
LEFT JOIN staging.dim_produto dp ON dp.id_produto = s.id_produto
LEFT JOIN volatilidade v
    ON v.id_produto = s.id_produto
   AND v.id_localidade = s.id_localidade
LEFT JOIN unidade_fact uf
    ON uf.id_produto = s.id_produto
   AND uf.id_localidade = s.id_localidade
   AND uf.ano = s.ano
   AND uf.mes = s.mes
ORDER BY
    mudou_status DESC,
    prioridade_alvo DESC,
    distancia_referencia DESC
LIMIT 1000;

COMMENT ON VIEW ops.simulacao_semaforo_v82 IS
    'Validation Gate da Migration 82: compara status_cor atual (regra antiga) '
    'com a regra sensível por CV, expõe cv_real/contam_unidade/unidade_inferida '
    'e metadado_transparencia. Prioriza mudanças de status, produtos '
    'PITAYA/BATATA/ALFACE e maiores distâncias |preco_atual - referência|. '
    'LIMIT 1000 linhas mais críticas.';

GRANT SELECT ON ops.simulacao_semaforo_v82 TO role_api_reader, role_etl_writer;

-- ============================================================================
-- ROLLBACK (não executar — instruções para desfazer a Migration 82)
-- ============================================================================
-- 1. Restaurar UNIQUE antigo e remover colunas da fact:
--      ALTER TABLE staging.fact_precos_mensais
--          DROP CONSTRAINT IF EXISTS uq_fact_precos_mensais_unidade;
--      DROP INDEX IF EXISTS staging.uq_fact_precos_mensais_unidade;
--      ALTER TABLE staging.fact_precos_mensais
--          ADD CONSTRAINT uq_fact_precos_mensais UNIQUE (id_produto, id_localidade, ano, mes);
--      ALTER TABLE staging.fact_precos_mensais
--          DROP COLUMN IF EXISTS unidade_canonica,
--          DROP COLUMN IF EXISTS fator_kg,
--          DROP COLUMN IF EXISTS fluxo_unidade;
-- 2. Remover dimensão:
--      DROP TABLE IF EXISTS mart.dim_unidade_medida;
-- 3. Reverter funções do semáforo (recriar a 3-arg com banda absoluta da
--    migration 65 e remover as novas):
--      DROP FUNCTION IF EXISTS staging.calcular_semaforo_preco_sensivel(NUMERIC, NUMERIC, NUMERIC, NUMERIC);
--      DROP FUNCTION IF EXISTS staging.estatisticas_volatilidade_24m_cv();
--      DROP FUNCTION IF EXISTS staging.normalizar_unidade_sql(TEXT);
--      -- recriar staging.calcular_semaforo_preco(NUMERIC,NUMERIC,NUMERIC) a partir
--      -- da migration 65 (fn_status_cor_zscore) e reaplicar a migration 81 (renome).
-- 4. Reverter sazonalidade:
--      ALTER TABLE mart.sazonalidade_produto
--          DROP COLUMN IF EXISTS cv_serie,
--          DROP COLUMN IF EXISTS contam_unidade;
--      -- recriar staging.sp_calcular_sazonalidade a partir da migration 81.
-- 5. Remover view de auditoria:
--      DROP VIEW IF EXISTS ops.simulacao_semaforo_v82;
-- 6. Writers: reverter ON CONFLICT dos pipelines para a forma de 4 colunas.
